export class AppConstant {
  // archivos
  static readonly LOGS_REQUESTS_ARCHIVO_PATH = 'logs-request.txt';
  static readonly LOGS_ION_ARCHIVO_PATH = 'logs-ion.txt';

  static readonly ESTADO_DETALLE_ITEM_PRODUCTO_NO_REVISADO = 0;
  static readonly ESTADO_DETALLE_ITEM_PRODUCTO_NO_APROBADO = 1;
  static readonly ESTADO_DETALLE_ITEM_PRODUCTO_APROBADO = 2;
  static readonly ESTADO_DETALLE_ITEM_PRODUCTO_RETIRO = 3;
  static readonly ESTADO_DETALLE_ITEM_PRODUCTO_EGRESO = 4;

  static readonly ESTADO_SOLICITUD_PREVIA_CANCELADO = 0;
  static readonly ESTADO_SOLICITUD_PREVIA_CREADO = 1;
  static readonly ESTADO_SOLICITUD_PREVIA_MATRICULA = 2;
  static readonly ESTADO_SOLICITUD_PREVIA_TARJAS_COMPLETADAS = 3;

  static readonly ESTADO_SOLICITUD_PREVIA_DETALLE_NO_REVISADO = 0;
  static readonly ESTADO_SOLICITUD_PREVIA_DETALLE_CREADO = 1;
  static readonly ESTADO_SOLICITUD_DETALLE_EN_MATRICULA_AFIANZADA = 2;
  static readonly ESTADO_SOLICITUD_DETALLE_EN_TARJA = 3;

  static readonly ESTADO_MATRICULA_AFIANZADA_VIGENTE = 0;
  static readonly ESTADO_MATRICULA_AFIANZADA_ANULADO = 1;

  static readonly CODIGO_PROCESO_SOLICITUD_PREVIA = '001_SOLICITUD_PREVIA';
  static readonly CODIGO_PROCESO_MATRICULA_AFIANZADA = '002_MATRICULA_AFIANZADA';
  static readonly CODIGO_PROCESO_TARJA_RECEPCION = '003_TARJA_RECEPCION';
  static readonly CODIGO_PROCESO_NOTIFICACION_RETIRO = '004_NOTIFICACION_RETIRO';
  static readonly CODIGO_PROCESO_NOTIFICACION_EGRESO_VEHICULO = '005_NOTIFICACION_EGRESO_VEHICULO';
  static readonly CODIGO_PROCESO_FACTURA_INFORMATIVA = '006_FACTURA_INFORMATIVA';

  static readonly ESTADO_RACK_DISPONIBLE = 1;
  static readonly ESTADO_RACK_OCUPADO = 2;
  static readonly ESTADO_RACK_DESHABILITADO = 0;

  static readonly TIPO_NOTIFICACION_RETIRO_TOTAL = 2;
  static readonly TIPO_NOTIFICACION_RETIRO_PARCIAL = 1;
  static readonly TEXTO_TIPO_NOTIFICACION_RETIRO_TOTAL_PARCIAL = ['TOTAL', 'PARCIAL'];

  static readonly ESTADO_NOTIFICACION_RETIRO_ANULADO = 0;
  static readonly ESTADO_NOTIFICACION_RETIRO_SIN_FACTURA_INFORMATIVA = 1;
  static readonly ESTADO_NOTIFICACION_RETIRO_FACTURA_INFORMATIVA = 2;

  static readonly ESTADO_PUERTO_EMBARQUE_HABILITADO = 1;
  static readonly ESTADO_PUERTO_EMBARQUE_DESHABILITADO = 0;
  static readonly ESTADO_PUERTO_DESPACHO_HABILITADO = 1;
  static readonly ESTADO_PUERTO_DESPACHO_DESHABILITADO = 0;
  static readonly ESTADO_PERSONA_AUTORIZADA_HABILITADO = 1;
  static readonly ESTADO_PERSONA_AUTORIZADA_DESHABILITADO = 0;

  static readonly TIPO_PERMISO_USUARIO_ACCION = 3;
  static readonly TIPO_PERMISO_USUARIO_PAGES = 2;
  static readonly TIPO_PERMISO_USUARIO_MODULO = 1;

  static readonly NOMBRE_EMPRESA = 'LMI (LMI)';

  static readonly ESTADO_FACTURA_INFORMATIVA_SIN_NOTIFICACION_EGRESO = 0;
  static readonly ESTADO_FACTURA_INFORMATIVA_CON_NOTIFICACION_EGRESO_PENDIENTES = 1;
  static readonly ESTADO_FACTURA_INFORMATIVA_CON_NOTIFICACION_EGRESO_COMPLETO = 2;
  static readonly ESTADO_FACTURA_INFORMATIVA_ANULADO = 3;

  static readonly ESTADO_NOTIFICACION_EGRESO_VIGENTE = 0;
  static readonly ESTADO_NOTIFICACION_EGRESO_ANULADO = 1;

  static readonly TIPO_RETIRO_NOTIFICACION_EGRESO_TOTAL = { etiqueta: 'TOTAL', valor: 0 };
  static readonly TIPO_RETIRO_NOTIFICACION_EGRESO_PARCIAL = { etiqueta: 'PARCIAL', valor: 1 };
  static readonly ESTADO_CONTROL_TARJA_CORRECTO = 1;
  static readonly ESTADO_CONTROL_TARJA_DEFECTUOSO = 0;

  static readonly ESTADO_INCIDENTE_HABILITADO = 1;
  static readonly ESTADO_INCIDENTE_DESHABILITADO = 0;

  static readonly ESTADO_PROCESO_HABILITADO = 1;
  static readonly ESTADO_PROCESO_DESHABILITADO = 0;

}
